/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const aws = {
    "aws_project_region": "us-east-1",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_8WfVM1lW6",
    "aws_user_pools_web_client_id": "76vmjcebgaq686fcns9mmnpg7n",
    "oauth": {}
};


export default aws;
